### ISSUE TITLE
DM questions

### ISSUE THREAD

**Issue by MiguelCarranza** [debugpolitics/debugbot#21]
### Overview
Every week, DebugBot DMs every user with a question. Eg: *Will you attend the LA event* Yes, No, Maybe.

### Information requirements
We need to store, at least:
* Questions, and when they should be scheduled
* Different options
* Answers from users

### Admin site
ActiveAdmin should have a new section for this questions

**Comment by avand** [comment]
Let's sit on this for a bit... discussion happening here:

https://docs.google.com/document/d/1uqsbJKSoRB6UwOxjKbsD0vjMR3SmhW_y7sc8H7jUOFs/edit
