### ISSUE TITLE
DMing /do to Debugbot sometimes returns an error

### ISSUE THREAD

**Issue by jessepickard** [debugpolitics/debugbot#5]
25% of the time when I type "/do" I get this in return: https://cl.ly/0d1S392W3a44

It most often happens after I haven't engaged with Debugbot for a while.

**Comment by MiguelCarranza** [comment]
oh, that one is a really easy fix. it's because heroku puts it to sleep as soon as it's unused, so the first request always times out. the fix is actually paying for Heroku (right now, it's using my free account)

**Comment by MiguelCarranza** [comment]
Fixed
