### ISSUE TITLE
Allow skill-specific tasks

### ISSUE THREAD

**Issue by jessepickard** [debugpolitics/debugbot#6]
It would be great to create Debugbot tasks that only show up for people with certain skill sets. For instance we could create a multi-use todo for developers that would say "complete a website GitHub website issue"

Could we make selecting a skill set part of the Debugbot admin account creation process? I imagine it would be pretty easy to tag tasks as "developer" or "designer"

cc @MiguelCarranza

**Comment by jessepickard** [comment]
When creating an admin task, the tags should be:
- Enginering
- Design
- Copywriting
- Sales
- Generic  (or we don't have the 'generic' tag and not selecting any tag means that the task shows up for everyone)

**Comment by jessepickard** [comment]
We also need to figure out how we get this information from people. My suggestion is that @debugbot should ask you in a DM after joining Slack.* 

"Hi Jesse! Do you have any of the following skills?
1 - Engineering
2 - Design
3 - Copywriting
4 - Sales

If you do, respond with a number '2' or multiple numbers separated by commas '2,3' 

With this info, Debugbot can you give you more tasks that are related to you skillset. Thanks! "


I also think that @debugbot should DM you each week to tell you how many points you've gotten and suggest a task to start, but I don't have copy for that yet. 

*For existing users, it would be great if we could push out the message to everyone when this project is complete, but if that's not possible we can manually assign skills with the admin.

**Comment by rmd6502** [comment]
@jessepickard recommend making the points DM described in your last update a separate task

**Comment by jessepickard** [comment]
@rmd6502 Done! You can find this task here: #14

**Comment by rmd6502** [comment]
Task screens should have category filter and checkboxes now.
